# Generated by Django 2.1.7 on 2019-06-12 06:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('about_main_pic', models.ImageField(blank=True, null=True, upload_to='header/')),
                ('about_pic', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('our_numbers', models.CharField(blank=True, max_length=200, null=True)),
                ('reload', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booktruck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('unapproved', models.BooleanField(blank=True, default=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('person_hiring_the_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_pic', models.ImageField(blank=True, null=True, upload_to='driver_images/')),
                ('age', models.CharField(max_length=200, null=True)),
                ('date_hired', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_number', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessee_images', models.ImageField(blank=True, null=True, upload_to='lessee_images/')),
                ('ministry', models.CharField(max_length=200, null=True)),
                ('ministry_address', models.CharField(max_length=100, null=True)),
                ('ministry_phone', models.CharField(max_length=100, null=True)),
                ('ministry_email', models.CharField(blank=True, max_length=100, null=True)),
                ('ministry_central_location', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='lesser_images/')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('central_location', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Onhire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_location', models.CharField(blank=True, max_length=200, null=True)),
                ('hire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Lessee')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_image', models.ImageField(blank=True, null=True, upload_to='truck_images/')),
                ('truck_name', models.CharField(max_length=200, null=True)),
                ('truck_color', models.CharField(blank=True, max_length=200, null=True)),
                ('truck_plates', models.CharField(max_length=200, null=True)),
                ('truck_description', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='onhire',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Truck'),
        ),
        migrations.AddField(
            model_name='onhire',
            name='truck_ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Lessor'),
        ),
        migrations.AddField(
            model_name='driver',
            name='truck_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Truck'),
        ),
    ]
