# Generated by Django 2.1.7 on 2019-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktruck',
            name='person_hiring_the_truck',
        ),
        migrations.AddField(
            model_name='booktruck',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booktruck',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booktruck',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
