# Generated by Django 2.1.7 on 2019-06-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190612_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktruck',
            name='unapproved',
        ),
    ]
