# Generated by Django 2.2.2 on 2019-06-10 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_lessee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('central_location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=200, null=True)),
                ('truck_color', models.CharField(blank=True, max_length=200, null=True)),
                ('truck_plates', models.CharField(max_length=200, null=True)),
                ('truck_description', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Onhire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_location', models.CharField(blank=True, max_length=200, null=True)),
                ('hire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Lessee')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Truck')),
                ('truck_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Lessor')),
            ],
        ),
    ]
