# Generated by Django 2.2.2 on 2019-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190611_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessee',
            name='lessee_images',
            field=models.ImageField(blank=True, null=True, upload_to='lessee_images/'),
        ),
        migrations.AddField(
            model_name='lessor',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesser_images/'),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_image',
            field=models.ImageField(blank=True, null=True, upload_to='truck_images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_pic',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
    ]
