# Generated by Django 2.2.2 on 2019-06-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190611_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_plates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
