# Generated by Django 2.2.2 on 2019-06-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190611_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='truck_plates',
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_plate_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
