# Generated by Django 2.2.2 on 2019-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_truck_truck_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_plates',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
