# Generated by Django 2.2.2 on 2019-06-11 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0010_truck_truck_plates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktruck',
            old_name='Person_hiring_the_truck',
            new_name='person_hiring_the_truck',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_pic', models.ImageField(blank=True, null=True, upload_to='driver_images/')),
                ('age', models.CharField(max_length=200, null=True)),
                ('date_hired', models.CharField(max_length=200, null=True)),
                ('id_number', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('truck_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Truck')),
            ],
        ),
    ]
