# Generated by Django 2.2.2 on 2019-06-11 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20190611_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='onhire',
            name='driver',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='booking.Driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_hired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
