# Generated by Django 2.2.2 on 2019-06-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20190611_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onhire',
            old_name='driver',
            new_name='driver_onhire',
        ),
    ]
