# Generated by Django 2.2.2 on 2019-06-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20190611_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onhire',
            name='driver_onhire',
        ),
    ]
